// Generates the committed artifacts from machine.ts:
//   - machine.json         runtime artifact the router workflows load
//   - BOT_STATE_MACHINE.md  diagram + transition table + command grammar
//
// Run: pnpm bot:generate   (or: npx tsx .github/bot/generate.ts)
// CI runs it with --check and fails if the committed files are stale.

import { writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
	ENTRY_STATE,
	EVENTS,
	KINDS,
	STATES,
	TRANSITIONS,
	type EventId,
	type StateId,
	kindLabels,
	machineSnapshot,
	stateLabels,
	validateMachine,
} from "./machine.ts";

const here = dirname(fileURLToPath(import.meta.url));
const jsonPath = join(here, "machine.json");
const docPath = join(here, "..", "BOT_STATE_MACHINE.md");

const check = process.argv.includes("--check");

// --- validate first ---
const problems = validateMachine();
if (problems.length) {
	console.error("Machine validation failed:");
	for (const p of problems) console.error(`  - ${p.message}`);
	process.exit(1);
}

// --- machine.json ---
const json = JSON.stringify(machineSnapshot(), null, "\t") + "\n";

// --- Mermaid diagram ---
function mermaid(): string {
	const lines = ["stateDiagram-v2", `    [*] --> ${ENTRY_STATE}: issue opened`];
	for (const t of TRANSITIONS) {
		// Skip idempotent self-loops in the diagram unless they carry meaning.
		const label = t.event.replace(/^agent\./, "").replace(/^pr\./, "PR ").replace(/_/g, " ");
		lines.push(`    ${t.from} --> ${t.to}: ${label}`);
	}
	// Style terminals and the working transient state.
	const terminals = (Object.keys(STATES) as StateId[]).filter((s) => STATES[s].terminal);
	lines.push(`    class ${terminals.join(",")} terminal`);
	lines.push("    class working transient");
	lines.push("    classDef terminal fill:#1b3a2b,stroke:#3fb950,color:#7ee787");
	lines.push("    classDef transient fill:#1f2937,stroke:#388bfd,color:#79c0ff");
	return lines.join("\n");
}

// --- transition table ---
function transitionTable(): string {
	const rows = TRANSITIONS.map((t) => {
		const actors = EVENTS[t.event].actors.join(", ");
		const action = t.action ? `\`${t.action}\`` : "—";
		return `| \`${t.from}\` | \`${t.event}\` | ${actors} | ${action} | \`${t.to}\` | ${t.note ?? ""} |`;
	});
	return ["| From | Event | Actors | Action | To | Note |", "| --- | --- | --- | --- | --- | --- |", ...rows].join("\n");
}

// --- command grammar ---
function grammar(): string {
	const verbs = (Object.keys(EVENTS) as EventId[]).filter((e) => EVENTS[e].actors.some((a) => a !== "system") && !e.includes("."));
	const rows = verbs.map((v) => {
		const m = EVENTS[v];
		const arg = m.arg ? ` <${m.arg}>` : "";
		const labels = m.labelTriggers?.length ? ` (or label \`${m.labelTriggers.join("`, `")}\`)` : "";
		return `| \`@emdashbot ${v.replace(/_/g, " ")}${arg}\`${labels} | ${m.actors.filter((a) => a !== "system").join(", ")} | ${m.description} |`;
	});
	return ["| Command | Who | Effect |", "| --- | --- | --- |", ...rows].join("\n");
}

// --- comment defaults (states where a bare @emdashbot comment maps to an event) ---
function commentDefaults(): string {
	const rows = (Object.keys(STATES) as StateId[])
		.filter((id) => STATES[id].defaultCommentEvent)
		.map((id) => `- In \`${id}\`, an \`@emdashbot\` comment that isn't a known verb is treated as \`${STATES[id].defaultCommentEvent}\` (the comment body becomes the argument).`);
	return rows.length
		? `An \`@emdashbot\` mention is always required; only the verb is optional in these states:\n\n${rows.join("\n")}`
		: "No states define an implicit comment event.";
}

// --- state table ---
function stateTable(): string {
	const rows = (Object.keys(STATES) as StateId[]).map((id) => {
		const s = STATES[id];
		const flags = [s.terminal ? "terminal" : "", s.transient ? "transient" : ""].filter(Boolean).join(", ") || "—";
		const label = s.label === "" ? "—" : `\`${s.label}\``;
		return `| \`${id}\` | ${label} | ${s.boardColumn} | ${flags} | ${s.description} |`;
	});
	return ["| State | Label | Board column | Flags | Meaning |", "| --- | --- | --- | --- | --- |", ...rows].join("\n");
}

const doc = `<!-- GENERATED by .github/bot/generate.ts from machine.ts. Do not edit by hand. -->

# emdashbot state machine

The single source of truth is [\`.github/bot/machine.ts\`](./bot/machine.ts). This file
and [\`machine.json\`](./bot/machine.json) are generated from it; CI fails if they drift.

A work item (an issue, plus its eventual PR) carries **exactly one \`kind\` label and
one \`state\` label** at all times. \`kind\` is the category; \`state\` is the lifecycle phase.

## Kinds

${KINDS.map((k) => `- \`bot:${k}\``).join("\n")}

## Lifecycle

\`\`\`mermaid
${mermaid()}
\`\`\`

## States

${stateTable()}

## Command grammar

Every command is spoken as \`@emdashbot <verb>\`; a few also have label shortcuts.
The bot ends each comment with the commands valid from the current state, so the
interface is self-documenting. \`@emdashbot status\` renders the item's position on demand.

${grammar()}

### Implicit feedback on a bot PR

${commentDefaults()}

## Transitions

Agent results (\`agent.*\`) and PR lifecycle events (\`pr.*\`) are fired by workflows,
not humans. The router looks up exactly one transition per (state, event); an event
with no transition from the current state is a no-op (the control listener replies
with the valid commands instead of erroring).

${transitionTable()}

## Labels to provision

Kinds: ${kindLabels().map((l) => `\`${l}\``).join(", ")}

States: ${stateLabels().map((l) => `\`${l}\``).join(", ")}
`;

if (check) {
	const jsonStale = readFileSync(jsonPath, "utf8") !== json;
	const docStale = readFileSync(docPath, "utf8") !== doc;
	if (jsonStale || docStale) {
		console.error("Generated bot artifacts are stale. Run `pnpm bot:generate` and commit.");
		if (jsonStale) console.error("  - machine.json differs");
		if (docStale) console.error("  - BOT_STATE_MACHINE.md differs");
		process.exit(1);
	}
	console.log("bot artifacts up to date");
} else {
	writeFileSync(jsonPath, json);
	writeFileSync(docPath, doc);
	console.log(`Wrote ${jsonPath}`);
	console.log(`Wrote ${docPath}`);
}
