/**
 * Plugin Wrapper Generator for workerd
 *
 * Generates the code that wraps a plugin to run in a workerd isolate.
 * Unlike the Cloudflare wrapper which uses RPC via service bindings,
 * this wrapper uses HTTP fetch to call the Node backing service.
 *
 * The wrapper:
 * - Imports plugin hooks and routes from "sandbox-plugin.js"
 * - Creates plugin context that proxies operations via HTTP to the backing service
 * - Exposes an HTTP fetch handler for hook/route invocation
 */

import { Buffer } from "node:buffer";

import { normalizeCapabilities, type PluginManifest } from "emdash";

const TRAILING_SLASH_RE = /\/$/;
const NEWLINE_RE = /[\n\r]/g;
const COMMENT_CLOSE_RE = /\*\//g;

const ROUTE_BYTES_MARKER = "__emdashBytes";
const ROUTE_ESCAPED_OBJECT_MARKER = "__emdashEscapedObject";

function isReservedRouteTransportObject(value: unknown): value is Record<string, unknown> {
	if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
	const keys = Object.keys(value);
	return (
		keys.length === 1 && (keys[0] === ROUTE_BYTES_MARKER || keys[0] === ROUTE_ESCAPED_OBJECT_MARKER)
	);
}

export function stringifyRouteTransport(value: unknown): string {
	return JSON.stringify(value, (_key, entry) => {
		if (entry instanceof Uint8Array) {
			return { [ROUTE_BYTES_MARKER]: Buffer.from(entry).toString("base64") };
		}
		if (isReservedRouteTransportObject(entry)) {
			return { [ROUTE_ESCAPED_OBJECT_MARKER]: Object.entries(entry) };
		}
		return entry;
	});
}

export function parseRouteTransport(value: string): unknown {
	return JSON.parse(value, (_key: string, entry: unknown) => {
		if (entry === null || typeof entry !== "object" || Array.isArray(entry)) return entry;
		const keys = Object.keys(entry);
		const bytes = Reflect.get(entry, ROUTE_BYTES_MARKER);
		if (keys.length === 1 && typeof bytes === "string") {
			return new Uint8Array(Buffer.from(bytes, "base64"));
		}
		const escaped = Reflect.get(entry, ROUTE_ESCAPED_OBJECT_MARKER);
		if (keys.length === 1 && Array.isArray(escaped)) {
			return Object.fromEntries(escaped);
		}
		return entry;
	});
}

export interface WrapperOptions {
	site?: {
		name: string;
		url: string;
		locale: string;
		trailingSlash?: "always" | "never" | "ignore";
	};
	/** URL of the Node backing service (e.g., http://127.0.0.1:18787) */
	backingServiceUrl: string;
	/** Auth token the plugin sends on outbound bridge calls to Node */
	authToken: string;
	/**
	 * Auth token the Node runner must send on inbound hook/route invocations.
	 * Prevents same-host attackers from invoking plugin hooks directly via
	 * the per-plugin TCP listener (which is exposed on 127.0.0.1).
	 */
	invokeToken: string;
}

export function generatePluginWrapper(manifest: PluginManifest, options: WrapperOptions): string {
	const site = options.site ?? { name: "", url: "", locale: "en" };
	const capabilities = normalizeCapabilities(manifest.capabilities);
	const hasReadUsers = capabilities.includes("users:read");
	const hasEmailSend = capabilities.includes("email:send");

	return `
// =============================================================================
// Sandboxed Plugin Wrapper (workerd)
// Generated by @emdash-cms/sandbox-workerd
// Plugin: ${sanitizeComment(manifest.id)}@${sanitizeComment(manifest.version)}
// =============================================================================

import pluginModule from "sandbox-plugin.js";

const hooks = pluginModule?.hooks || pluginModule?.default?.hooks || {};
const routes = pluginModule?.routes || pluginModule?.default?.routes || {};

const BACKING_URL = ${JSON.stringify(options.backingServiceUrl)};
const AUTH_TOKEN = ${JSON.stringify(options.authToken)};
const INVOKE_TOKEN = ${JSON.stringify(options.invokeToken)};

function routeTransportReplacer(_key, value) {
	if (value instanceof Uint8Array) {
		let binary = "";
		const chunkSize = 0x8000;
		for (let offset = 0; offset < value.byteLength; offset += chunkSize) {
			binary += String.fromCharCode(...value.subarray(offset, offset + chunkSize));
		}
		return { __emdashBytes: btoa(binary) };
	}
	if (value && typeof value === "object" && !Array.isArray(value)) {
		const keys = Object.keys(value);
		if (keys.length === 1 &&
			(keys[0] === "__emdashBytes" || keys[0] === "__emdashEscapedObject")) {
			return { __emdashEscapedObject: Object.entries(value) };
		}
	}
	return value;
}

function routeTransportReviver(_key, value) {
	if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== 1) return value;
	if (typeof value.__emdashBytes === "string") {
		const binary = atob(value.__emdashBytes);
		const bytes = new Uint8Array(binary.length);
		for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index);
		return bytes;
	}
	if (Array.isArray(value.__emdashEscapedObject)) {
		return Object.fromEntries(value.__emdashEscapedObject);
	}
	return value;
}

function routeJsonResponse(value) {
	return new Response(JSON.stringify(value, routeTransportReplacer), {
		headers: { "content-type": "application/json" },
	});
}

function storageObjectEntries(value) {
	if (!value || typeof value !== "object" || Array.isArray(value) ||
		(Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null) ||
		Object.getOwnPropertySymbols(value).length) {
		throw new TypeError("Storage update objects must be plain objects");
	}
	return Object.entries(value);
}

function copyStorageCondition(value, ancestors = new Set()) {
	if (value === null || typeof value === "string" || typeof value === "boolean") return value;
	if (typeof value === "number" && Number.isFinite(value)) return value;
	if (typeof value !== "object" || ancestors.has(value)) {
		throw new TypeError("Storage conditions must contain finite JSON values without cycles");
	}
	ancestors.add(value);
	let copied;
	if (Array.isArray(value)) {
		if (Object.getPrototypeOf(value) !== Array.prototype ||
			Object.getOwnPropertySymbols(value).length ||
			Object.keys(value).length !== value.length) {
			throw new TypeError("Storage condition arrays must contain only indexed values");
		}
		copied = Array.from({ length: value.length }, (_, index) =>
			copyStorageCondition(value[index], ancestors));
	} else {
		copied = Object.fromEntries(storageObjectEntries(value).map(([key, entry]) =>
			[key, copyStorageCondition(entry, ancestors)]));
	}
	ancestors.delete(value);
	return copied;
}

function copyStorageWhere(value) {
	return Object.fromEntries(storageObjectEntries(value).map(([field, condition]) => {
		if (condition === null || typeof condition !== "object") {
			return [field, copyStorageCondition(condition)];
		}
		const filter = Object.fromEntries(storageObjectEntries(condition));
		if (Array.isArray(filter.in)) {
			return [field, { in: copyStorageCondition(filter.in) }];
		}
		if (typeof filter.startsWith === "string") {
			return [field, { startsWith: filter.startsWith }];
		}
		const bounds = ["gt", "gte", "lt", "lte"]
			.filter((key) => Object.hasOwn(filter, key))
			.map((key) => [key, filter[key]]);
		if (bounds.length === 0) return [field, copyStorageCondition(filter)];
		const defined = bounds.filter(([, bound]) => bound !== undefined);
		if (defined.length === 0) {
			throw new TypeError("Storage range filter must contain a defined bound");
		}
		return [field, copyStorageCondition(Object.fromEntries(defined))];
	}));
}

function marshalStorageUpdate(value) {
	const entries = storageObjectEntries(value).map(([key, entry]) =>
		[key, key === "set" || key === "delta" ? entry :
			key === "where" ? copyStorageWhere(entry) : copyStorageCondition(entry)]);
	return Object.fromEntries(entries.flatMap(([key, entry]) => {
		if (key !== "set" && key !== "delta") return [[key, entry]];
		if (entry === undefined) return [];
		const fields = storageObjectEntries(entry)
			.filter(([, fieldValue]) => fieldValue !== undefined)
			.map(([field, fieldValue]) => {
				if (key === "delta") return [field, copyStorageCondition(fieldValue)];
				const serialized = JSON.stringify(fieldValue);
				if (serialized === undefined) {
					throw new TypeError("Storage set values must be JSON serializable");
				}
				return [field, JSON.parse(serialized)];
			});
		return [[key, Object.fromEntries(fields)]];
	}));
}

function storageSerializationErrorDetails(value) {
	if (!value || typeof value !== "object" ||
		value.code !== "STORAGE_SERIALIZATION_FAILURE" || value.retryable !== true ||
		(value.sqlState !== undefined && value.sqlState !== "40001" && value.sqlState !== "40P01")) return null;
	return {
		name: "StorageSerializationError",
		code: "STORAGE_SERIALIZATION_FAILURE",
		retryable: true,
		...(value.sqlState === undefined ? {} : { sqlState: value.sqlState }),
		message: "Storage write must be retried. Restart the transaction before retrying when using an explicit transaction.",
	};
}

function sandboxRouteErrorDetails(value) {
	if (!value || typeof value !== "object") return null;
	const code =
		value.code === "MEDIA_USAGE_ACTIVATION_IN_PROGRESS" ||
		value.code === "MEDIA_USAGE_ACTIVATION_CHECK_FAILED"
			? value.code
			: value.name === "MEDIA_USAGE_ACTIVATION_IN_PROGRESS" ||
				  value.name === "MEDIA_USAGE_ACTIVATION_CHECK_FAILED"
				? value.name
				: null;
	if (!code || (value.status !== undefined && value.status !== 503)) return null;
	return {
		code,
		message:
			code === "MEDIA_USAGE_ACTIVATION_IN_PROGRESS"
				? "Media usage activation is in progress"
				: "Unable to verify media usage activation state",
		status: 503,
	};
}

function sandboxRouteErrorResponse(error) {
	const details = sandboxRouteErrorDetails(error);
	return details
		? Response.json(
				{ __emdashSandboxRouteError: true, error: details },
				{ status: details.status },
			)
		: null;
}

// -----------------------------------------------------------------------------
// Bridge - HTTP calls to Node backing service
// -----------------------------------------------------------------------------

async function bridgeCall(method, body) {
	const res = await fetch(BACKING_URL + "/" + method, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			"Authorization": "Bearer " + AUTH_TOKEN,
		},
		body: JSON.stringify(body),
	});
	if (!res.ok) {
		const text = await res.text();
		try {
			const payload = JSON.parse(text);
			const storageDetails = storageSerializationErrorDetails(payload?.error);
			if (storageDetails) throw Object.assign(new Error(storageDetails.message), storageDetails);
			const details = sandboxRouteErrorDetails(payload?.error);
			if (details) {
				const error = Object.assign(new Error(details.message), details, {
					name: details.code,
				});
				throw error;
			}
		} catch (error) {
			if (sandboxRouteErrorDetails(error) || storageSerializationErrorDetails(error)) throw error;
		}
		throw new Error("Bridge call " + method + " failed: " + text);
	}
	const data = await res.json();
	if (
		method === "http/fetch" &&
		data.result?.body &&
		typeof data.result.body === "object" &&
		typeof data.result.body.__emdashBytes === "string"
	) {
		const binary = atob(data.result.body.__emdashBytes);
		const bytes = new Uint8Array(binary.length);
		for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
		data.result.body = bytes;
	}
	return data.result;
}

// -----------------------------------------------------------------------------
// Context Factory
// -----------------------------------------------------------------------------

function createContext() {
	const kv = {
		get: (key) => bridgeCall("kv/get", { key }),
		set: (key, value) => bridgeCall("kv/set", { key, value }),
		getVersioned: (key) => bridgeCall("kv/getVersioned", { key }),
		compareAndSet: (key, expectedRevision, value) => bridgeCall("kv/compareAndSet", { key, expectedRevision, value }),
		compareAndDelete: (key, expectedRevision) => bridgeCall("kv/compareAndDelete", { key, expectedRevision }),
		delete: (key) => bridgeCall("kv/delete", { key }),
		list: (prefix) => bridgeCall("kv/list", { prefix }),
	};

	function createStorageCollection(collectionName) {
		return {
			get: (id) => bridgeCall("storage/get", { collection: collectionName, id }),
			put: (id, data) => bridgeCall("storage/put", { collection: collectionName, id, data }),
			getVersioned: (id) => bridgeCall("storage/getVersioned", { collection: collectionName, id }),
			compareAndSet: (id, expectedRevision, data) => bridgeCall("storage/compareAndSet", { collection: collectionName, id, expectedRevision, data }),
			compareAndDelete: (id, expectedRevision) => bridgeCall("storage/compareAndDelete", { collection: collectionName, id, expectedRevision }),
			updateIf: async (id, args) => {
				if (typeof id !== "string") throw new TypeError("Storage ID must be a string");
				return bridgeCall("storage/updateIf", { collection: collectionName, id, args: marshalStorageUpdate(args) });
			},
			delete: (id) => bridgeCall("storage/delete", { collection: collectionName, id }),
			exists: async (id) => (await bridgeCall("storage/get", { collection: collectionName, id })) !== null,
			query: (opts) => bridgeCall("storage/query", { collection: collectionName, ...opts }),
			count: (where) => bridgeCall("storage/count", { collection: collectionName, where }),
			getMany: async (ids) => {
				// Bridge returns a list of [id, data] pairs (not a plain object)
				// so special IDs like "__proto__" survive transport. Convert
				// back to Map to match StorageCollection.getMany() contract.
				const entries = await bridgeCall("storage/getMany", { collection: collectionName, ids });
				return new Map(entries || []);
			},
			putMany: (items) => bridgeCall("storage/putMany", { collection: collectionName, items }),
			deleteMany: (ids) => bridgeCall("storage/deleteMany", { collection: collectionName, ids }),
		};
	}

	const storage = new Proxy({}, {
		get(_, collectionName) {
			if (typeof collectionName !== "string") return undefined;
			return createStorageCollection(collectionName);
		}
	});

	const content = {
		get: (collection, id) => bridgeCall("content/get", { collection, id }),
		list: (collection, opts) => bridgeCall("content/list", { collection, ...opts }),
		create: (collection, data, options) => bridgeCall("content/create", { collection, data, options }),
		update: (collection, id, data) => bridgeCall("content/update", { collection, id, data }),
		delete: (collection, id) => bridgeCall("content/delete", { collection, id }),
		createMany: (collection, items) => bridgeCall("content/createMany", { collection, items }),
		updateMany: (collection, items) => bridgeCall("content/updateMany", { collection, items }),
		deleteMany: (collection, ids) => bridgeCall("content/deleteMany", { collection, ids }),
	};

	// Taxonomy access (read-only) - capability enforced by the bridge
	const taxonomies = {
		getAll: (opts) => bridgeCall("taxonomy/list", { ...opts }),
		getTerms: (taxonomy, opts) => bridgeCall("taxonomy/terms", { taxonomy, ...opts }),
		getEntryTerms: (collection, entryId, opts) => bridgeCall("taxonomy/entryTerms", { collection, entryId, ...opts }),
	};

	const media = {
		get: (id) => bridgeCall("media/get", { id }),
		list: (opts) => bridgeCall("media/list", opts || {}),
		upload: (filename, contentType, bytes) => {
			// Convert any binary input into a Uint8Array view pointing at the
			// SAME underlying bytes (not reinterpreted). For ArrayBufferView
			// inputs (Uint16Array, Int32Array, DataView, etc.) we must use
			// the view's buffer + byteOffset + byteLength so we don't
			// reinterpret element-typed values as bytes and corrupt the file.
			let view;
			if (bytes instanceof Uint8Array) {
				view = bytes;
			} else if (bytes instanceof ArrayBuffer) {
				view = new Uint8Array(bytes);
			} else if (ArrayBuffer.isView(bytes)) {
				view = new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
			} else {
				throw new TypeError("media.upload: bytes must be ArrayBuffer or ArrayBufferView");
			}
			let binary = "";
			for (let i = 0; i < view.length; i++) binary += String.fromCharCode(view[i]);
			return bridgeCall("media/upload", {
				filename,
				contentType,
				bytes: btoa(binary),
				encoding: "base64",
			});
		},
		getUploadUrl: () => { throw new Error("getUploadUrl is not available in sandbox mode. Use media.upload() instead."); },
		delete: (id) => bridgeCall("media/delete", { id }),
	};

	// Marshal a RequestInit into a bounded JSON-safe shape. Request performs the
	// standard BodyInit encoding before the decoded bytes are measured.
	async function marshalRequestInit(init) {
		if (!init) return undefined;
		const out = {};
		if (init.method) out.method = init.method;
		if (init.redirect) out.redirect = init.redirect;
		let body = init.body;
		const isBodyInit =
			typeof body === "string" ||
			body instanceof URLSearchParams ||
			body instanceof ArrayBuffer ||
			ArrayBuffer.isView(body) ||
			(typeof Blob !== "undefined" && body instanceof Blob) ||
			(typeof FormData !== "undefined" && body instanceof FormData) ||
			(typeof ReadableStream !== "undefined" && body instanceof ReadableStream);
		if (body !== undefined && body !== null && !isBodyInit) body = JSON.stringify(body);
		const request = new Request("https://plugin-http.invalid/", {
			...init,
			body,
			method: init.method || "POST",
			duplex: "half",
		});
		const headers = Array.from(request.headers.entries());
		if (headers.length > 0) out.headers = headers;
		if (request.body) {
			const reader = request.body.getReader();
			const chunks = [];
			let total = 0;
			try {
				while (true) {
					const { done, value } = await reader.read();
					if (done) break;
					total += value.byteLength;
					if (total > 8 * 1024 * 1024) {
						try { await reader.cancel(); } catch {}
						throw new Error("Plugin HTTP request body exceeds the 8388608 byte limit");
					}
					chunks.push(value);
				}
			} finally {
				reader.releaseLock();
			}
			const bytes = new Uint8Array(total);
			let offset = 0;
			for (const chunk of chunks) {
				bytes.set(chunk, offset);
				offset += chunk.byteLength;
			}
			let binary = "";
			for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
			out.bodyType = "base64";
			out.body = btoa(binary);
		}
		return out;
	}

	function decorateHttpResponse(response, finalUrl, redirected) {
		const clone = response.clone.bind(response);
		Object.defineProperties(response, {
			url: { configurable: true, value: finalUrl },
			redirected: { configurable: true, value: redirected },
			clone: {
				configurable: true,
				value: () => decorateHttpResponse(clone(), finalUrl, redirected),
			},
		});
		return response;
	}

	function responseFromHttpWire(result) {
		const nullBodyStatus = result.status === 101 || result.status === 204 || result.status === 205 || result.status === 304;
		const response = new Response(nullBodyStatus ? null : result.body, {
			status: result.status,
			statusText: result.statusText,
			headers: result.headers,
		});
		return decorateHttpResponse(response, result.finalUrl, result.redirected);
	}

	const http = {
		fetch: async (url, init) => {
			const marshaledInit = await marshalRequestInit(init);
			const result = await bridgeCall("http/fetch", { url, init: marshaledInit });
			return responseFromHttpWire(result);
		}
	};

	const log = {
		debug: (msg, data) => bridgeCall("log", { level: "debug", msg, data }),
		info: (msg, data) => bridgeCall("log", { level: "info", msg, data }),
		warn: (msg, data) => bridgeCall("log", { level: "warn", msg, data }),
		error: (msg, data) => bridgeCall("log", { level: "error", msg, data }),
	};

	const site = ${JSON.stringify(site)};
	const siteBaseUrl = ${JSON.stringify(site.url.replace(TRAILING_SLASH_RE, ""))};

	function url(path) {
		if (!path.startsWith("/")) {
			throw new Error('URL path must start with "/", got: "' + path + '"');
		}
		if (path.startsWith("//")) {
			throw new Error('URL path must not be protocol-relative, got: "' + path + '"');
		}
		return siteBaseUrl + path;
	}

	const users = ${hasReadUsers} ? {
		get: (id) => bridgeCall("users/get", { id }),
		getByEmail: (email) => bridgeCall("users/getByEmail", { email }),
		list: (opts) => bridgeCall("users/list", opts || {}),
	} : undefined;

	const email = ${hasEmailSend} ? {
		send: (message) => bridgeCall("email/send", { message }),
	} : undefined;

	const cron = {
		schedule: (name, opts) => bridgeCall("cron/schedule", { name, ...opts }),
		cancel: (name) => bridgeCall("cron/cancel", { name }),
		list: () => bridgeCall("cron/list", {}),
	};

	return {
		plugin: {
			id: ${JSON.stringify(manifest.id)},
			version: ${JSON.stringify(manifest.version || "0.0.0")},
		},
		storage,
		kv,
		content,
		taxonomies,
		media,
		http,
		log,
		site,
		url,
		users,
		email,
		cron,
	};
}

// -----------------------------------------------------------------------------
// HTTP Handler (replaces WorkerEntrypoint for workerd-on-Node)
// -----------------------------------------------------------------------------

// Constant-time string comparison. workerd doesn't expose
// crypto.timingSafeEqual, so XOR char codes manually. Always processes
// the full length of the longer input to avoid early-exit timing leaks.
function constantTimeEqual(a, b) {
	let result = a.length === b.length ? 0 : 1;
	const len = Math.max(a.length, b.length);
	for (let i = 0; i < len; i++) {
		const ac = i < a.length ? a.charCodeAt(i) : 0;
		const bc = i < b.length ? b.charCodeAt(i) : 0;
		result |= ac ^ bc;
	}
	return result === 0;
}

export default {
	async fetch(request) {
		const url = new URL(request.url);

		// Authenticate the caller. The plugin's TCP listener is exposed on
		// 127.0.0.1, so any local process could otherwise invoke hooks/routes
		// directly. Only the Node runner has the per-startup invoke token.
		// Use constant-time comparison: workerd doesn't expose timingSafeEqual,
		// so we XOR character codes manually. Same length always required.
		const authHeader = request.headers.get("authorization") || "";
		const expected = "Bearer " + INVOKE_TOKEN;
		if (!constantTimeEqual(authHeader, expected)) {
			return new Response("Unauthorized", { status: 401 });
		}

		if (url.pathname === "/__ready") {
			return new Response("ok", { status: 200 });
		}

		// Hook invocation: POST /hook/{hookName}
		if (url.pathname.startsWith("/hook/")) {
			const hookName = url.pathname.slice(6); // Remove "/hook/"
			const { event } = await request.json();
			const ctx = createContext();

			const hookDef = hooks[hookName];
			if (!hookDef) {
				return Response.json({ value: undefined });
			}

			const handler = typeof hookDef === "function" ? hookDef : hookDef.handler;
			if (typeof handler !== "function") {
				return new Response("Hook " + hookName + " handler is not a function", { status: 500 });
			}

			try {
				const result = await handler(event, ctx);
				return Response.json({ value: result });
			} catch (err) {
				return new Response(err.message || "Hook error", { status: 500 });
			}
		}

		// Route invocation: POST /route/{routeName}
		if (url.pathname.startsWith("/route/")) {
			const routeName = url.pathname.slice(7); // Remove "/route/"
			const { input, request: serializedRequest } = JSON.parse(
				await request.text(),
				routeTransportReviver,
			);
			const ctx = createContext();

			const route = routes[routeName];
			if (!route) {
				return new Response("Route not found: " + routeName, { status: 404 });
			}

			const handler = typeof route === "function" ? route : route.handler;
			if (typeof handler !== "function") {
				return new Response("Route " + routeName + " handler is not a function", { status: 500 });
			}

			try {
				// user: authenticated caller for private routes, resolved by
				// the host before dispatch.
				const result = await handler(
					{
						input,
						request: serializedRequest,
						requestMeta: serializedRequest?.meta,
						user: serializedRequest?.user,
					},
					ctx,
				);
				return routeJsonResponse(result);
			} catch (err) {
				const sandboxError = sandboxRouteErrorResponse(err);
				if (sandboxError) return sandboxError;
				return new Response(err.message || "Route error", { status: 500 });
			}
		}

		return new Response("Not found", { status: 404 });
	}
};
`;
}

function sanitizeComment(s: string): string {
	return s.replace(NEWLINE_RE, " ").replace(COMMENT_CLOSE_RE, "* /");
}
