/**
 * Plugin Wrapper Generator for workerd
 *
 * Generates the code that wraps a plugin to run in a workerd isolate.
 * Unlike the Cloudflare wrapper which uses RPC via service bindings,
 * this wrapper uses HTTP fetch to call the Node backing service.
 *
 * The wrapper:
 * - Imports plugin hooks and routes from "sandbox-plugin.js"
 * - Creates plugin context that proxies operations via HTTP to the backing service
 * - Exposes an HTTP fetch handler for hook/route invocation
 */

import type { PluginManifest } from "emdash";

const TRAILING_SLASH_RE = /\/$/;
const NEWLINE_RE = /[\n\r]/g;
const COMMENT_CLOSE_RE = /\*\//g;

export interface WrapperOptions {
	site?: { name: string; url: string; locale: string };
	/** URL of the Node backing service (e.g., http://127.0.0.1:18787) */
	backingServiceUrl: string;
	/** Auth token for this plugin's backing service requests */
	authToken: string;
}

export function generatePluginWrapper(manifest: PluginManifest, options: WrapperOptions): string {
	const site = options.site ?? { name: "", url: "", locale: "en" };
	const hasReadUsers = manifest.capabilities.includes("read:users");
	const hasEmailSend = manifest.capabilities.includes("email:send");

	return `
// =============================================================================
// Sandboxed Plugin Wrapper (workerd)
// Generated by @emdash-cms/workerd
// Plugin: ${sanitizeComment(manifest.id)}@${sanitizeComment(manifest.version)}
// =============================================================================

import pluginModule from "sandbox-plugin.js";

const hooks = pluginModule?.hooks || pluginModule?.default?.hooks || {};
const routes = pluginModule?.routes || pluginModule?.default?.routes || {};

const BACKING_URL = ${JSON.stringify(options.backingServiceUrl)};
const AUTH_TOKEN = ${JSON.stringify(options.authToken)};

// -----------------------------------------------------------------------------
// Bridge - HTTP calls to Node backing service
// -----------------------------------------------------------------------------

async function bridgeCall(method, body) {
	const res = await fetch(BACKING_URL + "/" + method, {
		method: "POST",
		headers: {
			"Content-Type": "application/json",
			"Authorization": "Bearer " + AUTH_TOKEN,
		},
		body: JSON.stringify(body),
	});
	if (!res.ok) {
		const text = await res.text();
		throw new Error("Bridge call " + method + " failed: " + text);
	}
	const data = await res.json();
	return data.result;
}

// -----------------------------------------------------------------------------
// Context Factory
// -----------------------------------------------------------------------------

function createContext() {
	const kv = {
		get: (key) => bridgeCall("kv/get", { key }),
		set: (key, value) => bridgeCall("kv/set", { key, value }),
		delete: (key) => bridgeCall("kv/delete", { key }),
		list: (prefix) => bridgeCall("kv/list", { prefix }),
	};

	function createStorageCollection(collectionName) {
		return {
			get: (id) => bridgeCall("storage/get", { collection: collectionName, id }),
			put: (id, data) => bridgeCall("storage/put", { collection: collectionName, id, data }),
			delete: (id) => bridgeCall("storage/delete", { collection: collectionName, id }),
			exists: async (id) => (await bridgeCall("storage/get", { collection: collectionName, id })) !== null,
			query: (opts) => bridgeCall("storage/query", { collection: collectionName, ...opts }),
			count: (where) => bridgeCall("storage/count", { collection: collectionName, where }),
			getMany: (ids) => bridgeCall("storage/getMany", { collection: collectionName, ids }),
			putMany: (items) => bridgeCall("storage/putMany", { collection: collectionName, items }),
			deleteMany: (ids) => bridgeCall("storage/deleteMany", { collection: collectionName, ids }),
		};
	}

	const storage = new Proxy({}, {
		get(_, collectionName) {
			if (typeof collectionName !== "string") return undefined;
			return createStorageCollection(collectionName);
		}
	});

	const content = {
		get: (collection, id) => bridgeCall("content/get", { collection, id }),
		list: (collection, opts) => bridgeCall("content/list", { collection, ...opts }),
		create: (collection, data) => bridgeCall("content/create", { collection, data }),
		update: (collection, id, data) => bridgeCall("content/update", { collection, id, data }),
		delete: (collection, id) => bridgeCall("content/delete", { collection, id }),
	};

	const media = {
		get: (id) => bridgeCall("media/get", { id }),
		list: (opts) => bridgeCall("media/list", opts || {}),
		upload: (filename, contentType, bytes) => bridgeCall("media/upload", { filename, contentType, bytes: Array.from(bytes) }),
		getUploadUrl: () => { throw new Error("getUploadUrl is not available in sandbox mode. Use media.upload() instead."); },
		delete: (id) => bridgeCall("media/delete", { id }),
	};

	const http = {
		fetch: async (url, init) => {
			const result = await bridgeCall("http/fetch", { url, init });
			return {
				status: result.status,
				ok: result.status >= 200 && result.status < 300,
				headers: new Headers(result.headers),
				text: async () => result.text,
				json: async () => JSON.parse(result.text),
			};
		}
	};

	const log = {
		debug: (msg, data) => bridgeCall("log", { level: "debug", msg, data }),
		info: (msg, data) => bridgeCall("log", { level: "info", msg, data }),
		warn: (msg, data) => bridgeCall("log", { level: "warn", msg, data }),
		error: (msg, data) => bridgeCall("log", { level: "error", msg, data }),
	};

	const site = ${JSON.stringify(site)};
	const siteBaseUrl = ${JSON.stringify(site.url.replace(TRAILING_SLASH_RE, ""))};

	function url(path) {
		if (!path.startsWith("/")) {
			throw new Error('URL path must start with "/", got: "' + path + '"');
		}
		if (path.startsWith("//")) {
			throw new Error('URL path must not be protocol-relative, got: "' + path + '"');
		}
		return siteBaseUrl + path;
	}

	const users = ${hasReadUsers} ? {
		get: (id) => bridgeCall("users/get", { id }),
		getByEmail: (email) => bridgeCall("users/getByEmail", { email }),
		list: (opts) => bridgeCall("users/list", opts || {}),
	} : undefined;

	const email = ${hasEmailSend} ? {
		send: (message) => bridgeCall("email/send", { message }),
	} : undefined;

	return {
		plugin: {
			id: ${JSON.stringify(manifest.id)},
			version: ${JSON.stringify(manifest.version || "0.0.0")},
		},
		storage,
		kv,
		content,
		media,
		http,
		log,
		site,
		url,
		users,
		email,
	};
}

// -----------------------------------------------------------------------------
// HTTP Handler (replaces WorkerEntrypoint for workerd-on-Node)
// -----------------------------------------------------------------------------

export default {
	async fetch(request) {
		const url = new URL(request.url);

		// Hook invocation: POST /hook/{hookName}
		if (url.pathname.startsWith("/hook/")) {
			const hookName = url.pathname.slice(6); // Remove "/hook/"
			const { event } = await request.json();
			const ctx = createContext();

			const hookDef = hooks[hookName];
			if (!hookDef) {
				return Response.json({ value: undefined });
			}

			const handler = typeof hookDef === "function" ? hookDef : hookDef.handler;
			if (typeof handler !== "function") {
				return new Response("Hook " + hookName + " handler is not a function", { status: 500 });
			}

			try {
				const result = await handler(event, ctx);
				return Response.json({ value: result });
			} catch (err) {
				return new Response(err.message || "Hook error", { status: 500 });
			}
		}

		// Route invocation: POST /route/{routeName}
		if (url.pathname.startsWith("/route/")) {
			const routeName = url.pathname.slice(7); // Remove "/route/"
			const { input, request: serializedRequest } = await request.json();
			const ctx = createContext();

			const route = routes[routeName];
			if (!route) {
				return new Response("Route not found: " + routeName, { status: 404 });
			}

			const handler = typeof route === "function" ? route : route.handler;
			if (typeof handler !== "function") {
				return new Response("Route " + routeName + " handler is not a function", { status: 500 });
			}

			try {
				const result = await handler(
					{ input, request: serializedRequest, requestMeta: serializedRequest?.meta },
					ctx,
				);
				return Response.json(result);
			} catch (err) {
				return new Response(err.message || "Route error", { status: 500 });
			}
		}

		return new Response("Not found", { status: 404 });
	}
};
`;
}

function sanitizeComment(s: string): string {
	return s.replace(NEWLINE_RE, " ").replace(COMMENT_CLOSE_RE, "* /");
}
