/**
 * Email Settings — Cloudflare Email binding check
 *
 * POST /_emdash/api/settings/email/test-binding
 *
 * Reports whether the Cloudflare `send_email` binding is present in the
 * Worker runtime. Does not send an email — only checks the binding exists,
 * so admins can validate their wrangler.jsonc before configuring the provider.
 */

import type { APIRoute } from "astro";

import { requirePerm } from "#api/authorize.js";
import { apiError, apiSuccess, handleError } from "#api/error.js";

export const prerender = false;

export const POST: APIRoute = async ({ locals }) => {
	const { emdash, user } = locals;

	if (!emdash?.db) {
		return apiError("NOT_CONFIGURED", "EmDash is not initialized", 500);
	}

	const denied = requirePerm(user, "settings:manage");
	if (denied) return denied;

	try {
		// Check the actual send_email binding from the Cloudflare Workers runtime.
		// The built-in provider is always registered, so we must verify the
		// binding itself rather than the plugin's presence.
		// @ts-ignore - virtual module, generated by the Astro integration
		const { env } = (await import("virtual:emdash/env")) as {
			env?: Record<string, unknown>;
		};
		if (!env) {
			return apiSuccess({
				available: false,
				message:
					"Cloudflare Workers runtime not detected. The send_email binding only works on Cloudflare Workers (deployed or via astro dev with the Cloudflare adapter).",
			});
		}
		// eslint-disable-next-line typescript/no-unsafe-type-assertion -- binding shape validated by the send() check below
		const binding = env.EMAIL as { send?: unknown } | undefined;

		if (!binding || typeof binding.send !== "function") {
			return apiSuccess({
				available: false,
				message:
					'send_email binding "EMAIL" not found. Add it to wrangler.jsonc: "send_email": [{ "name": "EMAIL" }], then redeploy.',
			});
		}

		return apiSuccess({
			available: true,
			message: "Cloudflare Email binding is available.",
		});
	} catch (error) {
		return handleError(error, "Failed to test binding", "EMAIL_BINDING_TEST_ERROR");
	}
};
