function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

async function loadVirtualEnv(): Promise<Record<string, unknown> | undefined> {
	try {
		// @ts-ignore - virtual module, generated by the Astro integration
		const { env } = (await import("virtual:emdash/env")) as {
			env?: Record<string, unknown>;
		};
		if (isRecord(env)) return env;
		return undefined;
	} catch {
		return undefined;
	}
}

export async function resolveOAuthEnv(
	fallbackEnv: Record<string, unknown>,
): Promise<Record<string, unknown>> {
	const virtualEnv = await loadVirtualEnv();
	return virtualEnv ?? fallbackEnv;
}
