import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

const templateRoot = new URL("../../../templates/", import.meta.url);

describe("service-business template guidance", () => {
	for (const template of ["service-business", "service-business-cloudflare"]) {
		it(`${template} documents its generated routes and schema`, async () => {
			const guide = await readFile(new URL(`${template}/AGENTS.md`, templateRoot), "utf8");

			expect(guide).toContain("`/projects`");
			expect(guide).toContain("`/service-areas/[slug]`");
			expect(guide).toContain("`business_settings`");
			expect(guide).not.toContain("A portfolio for showcasing creative work");
			expect(guide).not.toContain("| Work index");
			expect(guide).not.toContain("`/work/[slug]`");
			expect(guide).not.toContain("Playfair Display");
		});

		it(`${template} ships generated collection types`, async () => {
			const types = await readFile(new URL(`${template}/emdash-env.d.ts`, templateRoot), "utf8");

			expect(types).toContain("// Generated by EmDash on dev server start");
			expect(types).toContain("export interface Project");
			expect(types).toContain("gallery?: { src: string; alt: string }[];");
			expect(types).toContain("short_description: string;");
		});

		it(`${template} applies every queried collection cache hint`, async () => {
			const files: Record<string, string[]> = {
				"src/pages/index.astro": [
					"servicesResult",
					"projectsResult",
					"reviewsResult",
					"faqsResult",
					"areasResult",
					"settingsResult",
					"certificatesResult",
				],
				"src/pages/about.astro": ["team", "certificates"],
				"src/pages/contact.astro": ["settings", "areas"],
				"src/pages/services/[slug].astro": ["cacheHint", "faqs.cacheHint"],
				"src/pages/service-areas/[slug].astro": ["cacheHint", "services.cacheHint"],
			};

			for (const [file, hints] of Object.entries(files)) {
				const source = await readFile(new URL(`${template}/${file}`, templateRoot), "utf8");
				for (const hint of hints) {
					const expression = hint.endsWith("cacheHint") ? hint : `${hint}.cacheHint`;
					expect(source).toContain(`Astro.cache.set(${expression})`);
				}
			}
		});
	}
});
