/**
 * Project-specific message types passed across binding boundaries.
 *
 * The Worker's `Env` type itself is generated by `wrangler types` into
 * `worker-configuration.d.ts` (committed alongside this file), exposed
 * globally as `Env` and via `Cloudflare.Env`. Re-running `wrangler types`
 * after editing `wrangler.jsonc` keeps it in sync.
 */

export interface DiscoveryJob {
	did: string;
	collection: string;
	rkey: string;
	operation: "create" | "update" | "delete";
	cid: string;
	/**
	 * The Jetstream-supplied (unverified) record bytes. Never trusted as an
	 * assessment input (spec §9.1) — the discovery consumer re-fetches and
	 * verifies the exact (uri, cid) from the publisher's PDS before doing
	 * anything else.
	 */
	jetstreamRecord?: unknown;
}
