/**
 * EmDash plugin registry aggregator: Worker entrypoint.
 *
 * Reading order for someone learning this code:
 *   1. `constants.ts` — protocol-level constants (NSIDs, etc.).
 *   2. `env.ts` — project-specific message types passed across binding
 *      boundaries. The Worker `Env` is generated by `wrangler types` into
 *      `worker-configuration.d.ts`.
 *   3. `records-do.ts` — Jetstream connection.
 *   4. `records-consumer.ts` — PDS-verified ingest.
 *   5. `routes/*.ts` — XRPC read endpoints.
 *
 * The fetch/queue/scheduled handlers below are wired but no-op for now;
 * the smoke test in `test/smoke.test.ts` proves migrations apply and the
 * Worker boots.
 */

import type { RecordsJob } from "./env.js";

export { RecordsJetstreamDO } from "./records-do.js";

export default {
	async fetch(_request: Request, _env: Env, _ctx: ExecutionContext): Promise<Response> {
		return new Response("emdash-aggregator: not yet implemented", {
			status: 503,
			headers: { "content-type": "text/plain" },
		});
	},

	async queue(_batch: MessageBatch<RecordsJob>, _env: Env, _ctx: ExecutionContext): Promise<void> {
		// PDS-verified ingest will land here.
	},

	async scheduled(_event: ScheduledEvent, _env: Env, _ctx: ExecutionContext): Promise<void> {
		// 6h reconciliation pass will land here.
	},
};
