/**
 * Built-in Cloudflare Email Provider
 *
 * Delivers EmDash emails through Cloudflare Email Sending via a
 * `send_email` Worker binding. Registered as a built-in provider so it
 * always appears in the Settings → Email provider list — no plugin
 * registration in astro.config.mjs required.
 *
 * Configuration (in priority order):
 * 1. Database (Settings → Email UI): fromName, fromEmail, replyTo
 * 2. Env vars: EMAIL_FROM_NAME, EMAIL_FROM_EMAIL, EMAIL_REPLY_TO
 *
 * The `send_email` binding is checked at delivery time (and via the
 * "Test binding" button in Settings → Email). If missing, delivery
 * fails with a clear, actionable error message.
 */

import type { Kysely } from "kysely";

import { OptionsRepository } from "../database/repositories/options.js";
import type { Database } from "../database/types.js";
import { definePlugin } from "./define-plugin.js";
import type { EmailDeliverEvent, PluginContext, ResolvedPlugin } from "./types.js";

/** Plugin ID for the built-in Cloudflare Email provider */
export const CLOUDFLARE_EMAIL_PLUGIN_ID = "emdash-cloudflare-email";

/** Options key prefix for Cloudflare Email settings */
export const CLOUDFLARE_OPTION_PREFIX = "emdash:email:cloudflare:";

/** Cloudflare Email configuration */
export interface CloudflareEmailConfig {
	fromName: string;
	fromEmail: string;
	replyTo?: string;
	/** Name of the send_email binding (default "EMAIL") */
	binding?: string;
}

/** Minimal shape of the Email Sending binding (`send_email` in wrangler). */
interface SendEmailBinding {
	send(message: {
		to: string | string[];
		from: { email: string; name?: string };
		subject: string;
		text?: string;
		html?: string;
		replyTo?: string;
	}): Promise<{ messageId?: string }>;
}

/**
 * Resolve the Worker env at delivery time.
 *
 * Hooks run without request context, so the binding cannot come from
 * `Astro.locals.runtime`. The `cloudflare:workers` module exposes the
 * same env to any code bundled into the Worker.
 */
async function loadWorkerEnv(): Promise<Record<string, unknown>> {
	// Virtual module resolves to the Worker's `env` under @astrojs/cloudflare
	// and to `undefined` on Node — never imports `cloudflare:workers` directly.
	// @ts-ignore - virtual module, generated by the Astro integration
	const { env } = (await import("virtual:emdash/env")) as {
		env?: Record<string, unknown>;
	};
	if (!env) {
		throw new Error(
			"[cloudflare-email] Cloudflare Worker env is not available — this provider " +
				"only runs on the Cloudflare Workers runtime (deployed or via astro dev " +
				"with the Cloudflare adapter).",
		);
	}
	return env;
}

/**
 * Build the email:deliver handler for Cloudflare Email Sending.
 *
 * Exported for testing — production code should use the built-in plugin
 * registration in the runtime.
 */
export function createCloudflareEmailDeliver(
	config: CloudflareEmailConfig,
	loadEnv: () => Promise<Record<string, unknown>> = loadWorkerEnv,
): (event: EmailDeliverEvent, ctx: PluginContext) => Promise<void> {
	const bindingName = config.binding ?? "EMAIL";
	const from = { email: config.fromEmail, name: config.fromName };

	return async (event, ctx) => {
		const { message } = event;
		const env = await loadEnv();
		// eslint-disable-next-line typescript/no-unsafe-type-assertion -- Worker binding accessed from untyped env object; the send() check below validates the shape
		const binding = env[bindingName] as SendEmailBinding | undefined;
		if (!binding || typeof binding.send !== "function") {
			throw new Error(
				`[cloudflare-email] send_email binding "${bindingName}" not found — ` +
					`declare it in the wrangler config ("send_email": [{ "name": "${bindingName}" }]).`,
			);
		}

		const result = await binding.send({
			from,
			to: message.to,
			subject: message.subject,
			text: message.text,
			...(message.html ? { html: message.html } : {}),
			...(config.replyTo ? { replyTo: config.replyTo } : {}),
		});

		ctx.log.info("email delivered via Cloudflare Email Sending", {
			to: message.to,
			subject: message.subject,
			messageId: result?.messageId,
		});
	};
}

/**
 * Load Cloudflare Email config from DB (options table).
 * Returns null if not configured.
 */
export async function loadCloudflareConfigFromDb(
	db: Kysely<Database>,
): Promise<CloudflareEmailConfig | null> {
	const repo = new OptionsRepository(db);
	const fromName = await repo.get<string>(`${CLOUDFLARE_OPTION_PREFIX}fromName`);
	const fromEmail = await repo.get<string>(`${CLOUDFLARE_OPTION_PREFIX}fromEmail`);
	const replyTo = await repo.get<string>(`${CLOUDFLARE_OPTION_PREFIX}replyTo`);

	if (!fromName || !fromEmail) return null;
	return {
		fromName,
		fromEmail,
		...(replyTo ? { replyTo } : {}),
	};
}

/**
 * Save Cloudflare Email config to DB (options table).
 */
export async function saveCloudflareConfigToDb(
	db: Kysely<Database>,
	config: CloudflareEmailConfig,
): Promise<void> {
	const repo = new OptionsRepository(db);
	await repo.set(`${CLOUDFLARE_OPTION_PREFIX}fromName`, config.fromName);
	await repo.set(`${CLOUDFLARE_OPTION_PREFIX}fromEmail`, config.fromEmail);
	// Keep the combined "from" for backward compat with the old API shape
	await repo.set(`${CLOUDFLARE_OPTION_PREFIX}from`, `${config.fromName} <${config.fromEmail}>`);
	if (config.replyTo) {
		await repo.set(`${CLOUDFLARE_OPTION_PREFIX}replyTo`, config.replyTo);
	} else {
		await repo.delete(`${CLOUDFLARE_OPTION_PREFIX}replyTo`);
	}
}

/**
 * Load Cloudflare Email config from env vars.
 * Returns null if not configured.
 */
export function loadCloudflareConfigFromEnv(): CloudflareEmailConfig | null {
	const fromName = process.env.EMAIL_FROM_NAME;
	const fromEmail = process.env.EMAIL_FROM_EMAIL;
	if (!fromName || !fromEmail) return null;
	return {
		fromName,
		fromEmail,
		...(process.env.EMAIL_REPLY_TO ? { replyTo: process.env.EMAIL_REPLY_TO } : {}),
	};
}

/**
 * Load Cloudflare Email config: DB first, then env fallback.
 * Returns null if neither is configured.
 */
export async function loadCloudflareConfig(
	db: Kysely<Database>,
): Promise<CloudflareEmailConfig | null> {
	const dbConfig = await loadCloudflareConfigFromDb(db);
	if (dbConfig) return dbConfig;
	return loadCloudflareConfigFromEnv();
}

/**
 * Create the built-in Cloudflare Email provider plugin.
 *
 * Always registered (even without config) so it appears in the provider
 * list. The handler fails with a clear error if the binding is missing
 * or the config is incomplete.
 */
export function createCloudflareEmailPlugin(config: CloudflareEmailConfig | null): ResolvedPlugin {
	return definePlugin({
		id: CLOUDFLARE_EMAIL_PLUGIN_ID,
		version: "1.0.0",
		capabilities: ["hooks.email-transport:register"],
		hooks: {
			"email:deliver": {
				exclusive: true,
				handler: async (event: EmailDeliverEvent, ctx: PluginContext) => {
					if (!config) {
						throw new Error(
							"[cloudflare-email] Not configured — set sender name and email in " +
								"Settings → Email, or set EMAIL_FROM_NAME / EMAIL_FROM_EMAIL env vars.",
						);
					}
					const deliver = createCloudflareEmailDeliver(config);
					await deliver(event, ctx);
				},
			},
		},
	});
}
