export { default as Hero } from "./Hero.astro";
export { default as Features } from "./Features.astro";
export { default as Testimonials } from "./Testimonials.astro";
export { default as Pricing } from "./Pricing.astro";
export { default as FAQ } from "./FAQ.astro";
export { default as Logos } from "./Logos.astro";
export { default as Split } from "./Split.astro";
export { default as Stats } from "./Stats.astro";
export { default as CTA } from "./CTA.astro";
