/**
 * Workers Cache (edge page cache) status + purge handlers.
 *
 * Uses the Cloudflare purge REST API (`purge_everything`) with the same
 * credentials as `cloudflareCache()` (`CF_ZONE_ID` + `CF_CACHE_PURGE_TOKEN`).
 * Safe when credentials are missing — status reports `configured: false`.
 */

import type { ApiResult } from "../types.js";

/** Cloudflare purge API base */
const CF_API_BASE = "https://api.cloudflare.com/client/v4";

const DEFAULT_ZONE_ID_ENV = "CF_ZONE_ID";
const DEFAULT_API_TOKEN_ENV = "CF_CACHE_PURGE_TOKEN";

export interface WorkersCacheStatus {
	/** Whether zone ID + purge token are available for edge cache purge. */
	configured: boolean;
}

export interface WorkersCachePurgeResult {
	/** Whether zone ID + purge token were available. */
	configured: boolean;
	/** True when Cloudflare accepted the purge request. */
	purged: boolean;
}

export interface WorkersCacheCredentials {
	zoneId: string;
	apiToken: string;
}

function readString(env: Record<string, unknown> | undefined, key: string): string | undefined {
	if (!env) return undefined;
	const value = env[key];
	return typeof value === "string" && value.length > 0 ? value : undefined;
}

/**
 * Resolve Worker/Node env bindings for cache-purge credentials.
 * Prefer `virtual:emdash/env` (Cloudflare bindings); fall back to
 * `import.meta.env` / `process.env` for Node and tests.
 */
export async function resolveWorkersCacheCredentials(
	overrides?: Partial<WorkersCacheCredentials> & {
		zoneIdEnvVar?: string;
		apiTokenEnvVar?: string;
	},
): Promise<WorkersCacheCredentials | null> {
	if (overrides?.zoneId && overrides?.apiToken) {
		return { zoneId: overrides.zoneId, apiToken: overrides.apiToken };
	}

	let envRecord: Record<string, unknown> | undefined;
	try {
		// @ts-ignore - virtual module, generated by the Astro integration
		const mod = (await import("virtual:emdash/env")) as {
			env?: Record<string, unknown>;
		};
		envRecord = mod.env;
	} catch {
		// Outside Vite/Astro (unit tests, CLI)
	}

	const metaEnv =
		typeof import.meta !== "undefined"
			? // eslint-disable-next-line typescript/no-unsafe-type-assertion -- import.meta.env is a string bag at runtime
				(import.meta.env as Record<string, unknown> | undefined)
			: undefined;
	const processEnv =
		typeof process !== "undefined" && process.env
			? // eslint-disable-next-line typescript/no-unsafe-type-assertion -- process.env values are string | undefined
				(process.env as Record<string, unknown>)
			: undefined;

	const env = envRecord ?? metaEnv ?? processEnv;
	const zoneKey = overrides?.zoneIdEnvVar ?? DEFAULT_ZONE_ID_ENV;
	const tokenKey = overrides?.apiTokenEnvVar ?? DEFAULT_API_TOKEN_ENV;

	const zoneId = overrides?.zoneId ?? readString(env, zoneKey);
	const apiToken = overrides?.apiToken ?? readString(env, tokenKey);

	if (!zoneId || !apiToken) return null;
	return { zoneId, apiToken };
}

/**
 * Report whether Workers Cache purge credentials are configured.
 */
export async function handleWorkersCacheStatus(
	credentials?: WorkersCacheCredentials | null,
): Promise<ApiResult<WorkersCacheStatus>> {
	try {
		const resolved =
			credentials === undefined ? await resolveWorkersCacheCredentials() : credentials;
		return { success: true, data: { configured: resolved !== null } };
	} catch {
		return {
			success: false,
			error: {
				code: "WORKERS_CACHE_STATUS_ERROR",
				message: "Failed to read Workers Cache status",
			},
		};
	}
}

/**
 * Purge all edge-cached responses for the zone (`purge_everything`).
 */
export async function handleWorkersCachePurge(
	credentials?: WorkersCacheCredentials | null,
	fetchImpl: typeof fetch = fetch,
): Promise<ApiResult<WorkersCachePurgeResult>> {
	try {
		const resolved =
			credentials === undefined ? await resolveWorkersCacheCredentials() : credentials;

		if (!resolved) {
			return {
				success: true,
				data: { configured: false, purged: false },
			};
		}

		const response = await fetchImpl(`${CF_API_BASE}/zones/${resolved.zoneId}/purge_cache`, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${resolved.apiToken}`,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ purge_everything: true }),
		});

		if (!response.ok) {
			const body = await response.text().catch(() => "");
			return {
				success: false,
				error: {
					code: "WORKERS_CACHE_PURGE_ERROR",
					message: `Workers Cache purge failed (${response.status})${body ? `: ${body}` : ""}`,
				},
			};
		}

		return {
			success: true,
			data: { configured: true, purged: true },
		};
	} catch (error) {
		const message = error instanceof Error ? error.message : "Unknown error";
		return {
			success: false,
			error: {
				code: "WORKERS_CACHE_PURGE_ERROR",
				message: `Failed to purge Workers Cache: ${message}`,
			},
		};
	}
}
