// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface BusinessSetting {
  id: string;
  slug: string | null;
  status: string;
  business_name: string;
  phone: string;
  email: string;
  street_address?: string;
  city?: string;
  region?: string;
  postal_code?: string;
  opening_hours?: string;
  price_range?: string;
  hero_heading?: string;
  hero_text?: string;
  primary_cta_label?: string;
  primary_cta_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Certificate {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  issuer?: string;
  credential?: string;
  logo_text?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  service?: string;
  location?: string;
  summary?: string;
  gallery?: { src: string; alt: string }[];
  result?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Review {
  id: string;
  slug: string | null;
  status: string;
  customer_name: string;
  quote: string;
  rating?: number;
  service?: string;
  location?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ServiceArea {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  region?: string;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  short_description: string;
  description?: PortableTextBlock[];
  icon?: string;
  starting_price?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Team {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role: string;
  bio?: string;
  years_experience?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    business_settings: BusinessSetting;
    certificates: Certificate;
    faqs: Faq;
    projects: Project;
    reviews: Review;
    service_areas: ServiceArea;
    services: Service;
    team: Team;
  }
}
